title: Bulk Reprocess
description: This is an updated simple test add-on
type: object
documents:
  - query
properties:
  sure:
    title: Are you sure you want to reprocess these documents?
    type: boolean
