title: Bulk Reprocess
description: >-
  This addon allows you to bulk reprocess documents that have failed to upload. 
  If they still fail to upload, use the Clear Failed Uploads Add-On to clear the failed documents
  and try re-uploading. If it is a large document set, use the batch upload script 
  https://www.muckrock.com/news/archives/2023/jan/27/introducing-documentclouds-bulk-upload-script/
type: object
documents:
  - query
  - selected
properties:
  sure:
    title: Are you sure you want to reprocess these documents?
    type: boolean
  force_ocr: 
    title: Force OCR?
    type: boolean
  language:
    title: OCR Language. 
    type: string
    description: View full list of languages here: https://www.documentcloud.org/help/api#languages
    default: eng
    enum: &langs
      - ara # Arabic
      - zho # Chinese (Simplified)
      - tra # Chinese (Traditional)
      - hrv # Croatian
      - dan # Danish
      - nld # Dutch
      - eng # English
      - fra # French
      - deu # German
      - heb # Hebrew
      - hun # Hungarian
      - ind # Indonesian
      - ita # Italian
      - jpn # Japanese
      - kor # Korean
      - nor # Norwegian
      - por # Portuguese
      - ron # Romanian
      - rus # Russian
      - spa # Spanish
      - swe # Swedish
      - ukr # Ukrainian
