title: Bulk Reprocess
description: >-
  This addon allows you to bulk reprocess documents that have failed to upload. 
  If they still fail to upload, use the Clear Failed Uploads Add-On to clear the failed documents
  and try re-uploading. If it is a large document set, use the batch upload script 
  https://www.muckrock.com/news/archives/2023/jan/27/introducing-documentclouds-bulk-upload-script/
type: object
documents:
  - query
  - selected
properties:
  sure:
    title: Are you sure you want to reprocess these documents?
    type: boolean
  force_ocr: 
    title: Force OCR?
    type: boolean
  ocr_engine:
    title: OCR Engine to apply (tesseract or textract)
    type: string 
    default: tesseract
