title: Bulk Reprocess
description: This is an updated simple test add-on
type: object
documents:
  - query
properties:
  ocr:
    title: OCR? 
    type: boolean
  document_language:
    title: Document Language
    type: string
    default: english
  ocr_engine: 
    title: OCR Engine
    type: string
    default: tesseract
    description: OCR Engine you would like to apply during the re-process. Amazon Textract requires AI credits. 
